apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "f007eaae-c2b9-4eca-9d5f-547394554bd9"
    keyvaultName: "kv-aks-devsec-oidc-bing0"
    tenantId: "dfffa5fb-35e7-4444-b92f-e6ae36aa0442"
    objects: |
      array:
        - |
          objectName: demo-secret
          objectType: secret
          objectVersion: ""