name: DevSecOps Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan Terraform
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          scan-ref: terraform/
          severity: HIGH,CRITICAL

      - name: Scan Kubernetes manifests
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          scan-ref: kubernetes/
          severity: HIGH,CRITICAL

      - name: Scan demo image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: busybox:1.36
          severity: HIGH,CRITICAL